### ISSUE TITLE
Roadmap to v3

### ISSUE THREAD

**Issue by coolaj86** [dashhive/DashHD.js#11]
- [x] Republish DashKeys with base58check + ripemd + utils
- [x] PR for all non-async updates (minimal API breaks) (#4)
- [x] PR for breaking Uint8Array changes #8 
- [x] PR for async updates (mantaining node v10 compat)
- [x] PR for hard-breaking changes (node v18 and browser only)
- [x] Rebrand: update LICENSE, README strings, etc
- [x] Update README to use Zoomonic seeds, keys, etc
- [ ] ~~`getPubkey()` for parity~~
- [x] rename some things `getXPrv()`? `getXPub()`? `getPrivate()`?

Next
- [x] Glossary
- [x] CLI
- [x] BIP-44 differences
- [x] secp256k1 edge case
- [x] Why is DASH `5'` and DASH testnet `1'`? https://github.com/satoshilabs/slips/blob/master/slip-0044.md
